name: flutter_task_planner_app

description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  percent_indicator: ^2.1.3
  fluentui_system_icons: ^1.1.163
  expansion_tile_card: ^2.0.0
  flutter_svg: ^0.22.0
  svg_icon: ^0.0.1
  flutter_statusbarcolor_ns: ^0.4.0
  provider: ^6.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  image_picker: ^0.8.5
  path: ^1.8.0
  path_provider: ^2.0.9
  fluttertoast: ^8.0.9
  flutter_native_splash: ^2.1.6
  dio: ^4.0.6
  http_parser: ^4.0.0
  flutter_spinkit: ^5.1.0
  flutter_local_notifications: ^9.5.3+1
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/intek_besar.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/piket.json
    - assets/images/
    - assets/icon/
    - assets/images/header.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
    
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
    
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 600
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700